### ISSUE TITLE
Black brush hard to see on dark/black background

### ISSUE THREAD

**Issue by arp242** [everestpipkin/image-scrubber#36]
Cool little tool :-)

I just noticed that the black brush is rather hard (or even impossible!) to see on a black background. Perhaps using something like a white outline or changing colours depending on the background colour might be better?

Here's the image I used for testing (just something I happened to have in my ~/, heh): https://user-images.githubusercontent.com/1032692/83760969-40cb4000-a6a8-11ea-9037-485eb218fe48.jpg

(perhaps not entirely the intended use case for this, but I thought it would be worth making a quick report about it nonetheless).

**Comment by everestpipkin** [comment]
PR #43 solves this!

**Comment by bMacSwigg** [comment]
I'm not sure if #43 completely addresses this -- I think there's an additional issue that the paint stroke itself, rather than just the cursor, can be hard to see against a black background.

This is probably low priority, since if the background is black enough that you can't see where you've blurred/painted, then it _probably_ doesn't have sensitive info that needs to be painted or blurred. But it might be worth keeping this issue open to track improving the contrast of the brush's path/stroke itself.
